/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_LF = 2,
  anon_sym_or = 3,
  anon_sym_pa = 4,
  anon_sym_tl = 5,
  sym_section = 6,
  sym_comment = 7,
  sym_text = 8,
  sym_blank_line = 9,
  sym_source_file = 10,
  sym__line = 11,
  sym_tagged_line = 12,
  sym_section_line = 13,
  sym_comment_line = 14,
  sym_tag = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_LF] = "\n",
  [anon_sym_or] = "or",
  [anon_sym_pa] = "pa",
  [anon_sym_tl] = "tl",
  [sym_section] = "section",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym_blank_line] = "blank_line",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_tagged_line] = "tagged_line",
  [sym_section_line] = "section_line",
  [sym_comment_line] = "comment_line",
  [sym_tag] = "tag",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_pa] = anon_sym_pa,
  [anon_sym_tl] = anon_sym_tl,
  [sym_section] = sym_section,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym_blank_line] = sym_blank_line,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_tagged_line] = sym_tagged_line,
  [sym_section_line] = sym_section_line,
  [sym_comment_line] = sym_comment_line,
  [sym_tag] = sym_tag,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pa] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tl] = {
    .visible = true,
    .named = false,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_tagged_line] = {
    .visible = true,
    .named = true,
  },
  [sym_section_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_comment = 1,
  field_section = 2,
  field_tag = 3,
  field_text = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_comment] = "comment",
  [field_section] = "section",
  [field_tag] = "tag",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_section, 0},
  [1] =
    {field_comment, 0},
  [2] =
    {field_tag, 0},
    {field_text, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '#', 16,
        '/', 1,
        ':', 10,
        ';', 16,
        '[', 6,
        'o', 5,
        'p', 3,
        't', 4,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == ']') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(2);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 19,
        '#', 16,
        '/', 1,
        ';', 16,
        '[', 6,
        'o', 5,
        'p', 3,
        't', 4,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 11,
        '#', 16,
        '/', 1,
        ';', 16,
        '[', 6,
        'o', 5,
        'p', 3,
        't', 4,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_pa);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_tl);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_section);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 17},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_pa] = ACTIONS(1),
    [anon_sym_tl] = ACTIONS(1),
    [sym_section] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(11),
    [sym__line] = STATE(2),
    [sym_tagged_line] = STATE(2),
    [sym_section_line] = STATE(2),
    [sym_comment_line] = STATE(2),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_or] = ACTIONS(5),
    [anon_sym_pa] = ACTIONS(5),
    [anon_sym_tl] = ACTIONS(5),
    [sym_section] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_blank_line] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_tagged_line] = STATE(3),
    [sym_section_line] = STATE(3),
    [sym_comment_line] = STATE(3),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_or] = ACTIONS(5),
    [anon_sym_pa] = ACTIONS(5),
    [anon_sym_tl] = ACTIONS(5),
    [sym_section] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_blank_line] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_tagged_line] = STATE(3),
    [sym_section_line] = STATE(3),
    [sym_comment_line] = STATE(3),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_or] = ACTIONS(19),
    [anon_sym_pa] = ACTIONS(19),
    [anon_sym_tl] = ACTIONS(19),
    [sym_section] = ACTIONS(22),
    [sym_comment] = ACTIONS(25),
    [sym_blank_line] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_LF,
    ACTIONS(35), 6,
      anon_sym_or,
      anon_sym_pa,
      anon_sym_tl,
      sym_section,
      sym_comment,
      sym_blank_line,
  [15] = 3,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_LF,
    ACTIONS(41), 6,
      anon_sym_or,
      anon_sym_pa,
      anon_sym_tl,
      sym_section,
      sym_comment,
      sym_blank_line,
  [30] = 3,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_LF,
    ACTIONS(47), 6,
      anon_sym_or,
      anon_sym_pa,
      anon_sym_tl,
      sym_section,
      sym_comment,
      sym_blank_line,
  [45] = 2,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(51), 5,
      anon_sym_or,
      anon_sym_pa,
      anon_sym_tl,
      sym_section,
      sym_comment,
  [57] = 2,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(55), 5,
      anon_sym_or,
      anon_sym_pa,
      anon_sym_tl,
      sym_section,
      sym_comment,
  [69] = 2,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(59), 5,
      anon_sym_or,
      anon_sym_pa,
      anon_sym_tl,
      sym_section,
      sym_comment,
  [81] = 1,
    ACTIONS(61), 1,
      anon_sym_COLON,
  [85] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [89] = 1,
    ACTIONS(65), 1,
      anon_sym_COLON,
  [93] = 1,
    ACTIONS(67), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 15,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 45,
  [SMALL_STATE(8)] = 57,
  [SMALL_STATE(9)] = 69,
  [SMALL_STATE(10)] = 81,
  [SMALL_STATE(11)] = 85,
  [SMALL_STATE(12)] = 89,
  [SMALL_STATE(13)] = 93,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_line, 1, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_line, 1, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 1, 0, 2),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 1, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_line, 3, 0, 3),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged_line, 3, 0, 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_line, 2, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_line, 2, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 2, 0, 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 2, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_line, 4, 0, 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged_line, 4, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lyr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lyr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
